export const dataTrend = [
  {
    type_of: "article",
    id: 2414558,
    title:
      'Join the Amazon Q Developer "Quack The Code" Challenge: $3,000 in Prizes!',
    description:
      "We're excited to announce our second partnered challenge with AWS.  Running through May 11, the...",
    readable_publish_date: "Apr 30",
    slug: "join-the-amazon-q-developer-quack-the-code-challenge-3000-in-prizes-ng5",
    path: "/devteam/join-the-amazon-q-developer-quack-the-code-challenge-3000-in-prizes-ng5",
    url: "https://dev.to/devteam/join-the-amazon-q-developer-quack-the-code-challenge-3000-in-prizes-ng5",
    comments_count: 5,
    public_reactions_count: 89,
    collection_id: null,
    published_timestamp: "2025-04-30T15:46:56Z",
    language: "en",
    subforem_id: 1,
    positive_reactions_count: 89,
    cover_image:
      "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F1st480lgb6z9kqsxlnwu.png",
    social_image:
      "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F1st480lgb6z9kqsxlnwu.png",
    canonical_url:
      "https://dev.to/devteam/join-the-amazon-q-developer-quack-the-code-challenge-3000-in-prizes-ng5",
    created_at: "2025-04-17T18:55:42Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2025-04-30T15:46:56Z",
    last_comment_at: "2025-05-01T01:06:32Z",
    reading_time_minutes: 7,
    tag_list: ["devchallenge", "awschallenge", "webdev", "ai"],
    tags: "devchallenge, awschallenge, webdev, ai",
    user: {
      name: "dev.to staff",
      username: "thepracticaldev",
      twitter_username: "ThePracticalDev",
      github_username: null,
      user_id: 3,
      website_url: "https://dev.to",
      profile_image:
        "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png",
      profile_image_90:
        "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png",
    },
    organization: {
      name: "The DEV Team",
      username: "devteam",
      slug: "devteam",
      profile_image:
        "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
      profile_image_90:
        "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
    },
  },
  {
    type_of: "article",
    id: 2448926,
    title: "Turbo Charge the Amazon Q Developer CLI with MCP Servers",
    description:
      "Recently, I blogged a 4 part series about how the Model Context Protocol (MCP) can provide the...",
    readable_publish_date: "Apr 30",
    slug: "turbo-charge-the-amazon-q-developer-cli-with-mcp-servers-fl5",
    path: "/aws/turbo-charge-the-amazon-q-developer-cli-with-mcp-servers-fl5",
    url: "https://dev.to/aws/turbo-charge-the-amazon-q-developer-cli-with-mcp-servers-fl5",
    comments_count: 2,
    public_reactions_count: 14,
    collection_id: null,
    published_timestamp: "2025-04-30T13:38:52Z",
    language: "en",
    subforem_id: 1,
    positive_reactions_count: 14,
    cover_image:
      "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F1h2kdfobwr0yaa0rvl4t.png",
    social_image:
      "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F1h2kdfobwr0yaa0rvl4t.png",
    canonical_url:
      "https://dev.to/aws/turbo-charge-the-amazon-q-developer-cli-with-mcp-servers-fl5",
    created_at: "2025-04-30T13:36:26Z",
    edited_at: "2025-04-30T13:48:02Z",
    crossposted_at: null,
    published_at: "2025-04-30T13:38:52Z",
    last_comment_at: "2025-04-30T18:26:43Z",
    reading_time_minutes: 6,
    tag_list: ["aws", "mcp", "amazonivs"],
    tags: "aws, mcp, amazonivs",
    user: {
      name: "Todd Sharp",
      username: "recursivecodes",
      twitter_username: "recursivecodes",
      github_username: "recursivecodes",
      user_id: 895331,
      website_url: "https://recursive.codes",
      profile_image:
        "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F895331%2F59774920-1938-4c2e-b293-efa14fe46948.jpg",
      profile_image_90:
        "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F895331%2F59774920-1938-4c2e-b293-efa14fe46948.jpg",
    },
    organization: {
      name: "AWS",
      username: "aws",
      slug: "aws",
      profile_image:
        "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1726%2Fe01690b9-c8bd-4eb9-bbe2-a4db25a702a9.png",
      profile_image_90:
        "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1726%2Fe01690b9-c8bd-4eb9-bbe2-a4db25a702a9.png",
    },
  },
  {
    type_of: "article",
    id: 2449667,
    title: "Will AI Ruin Society?",
    description:
      "Spoiler Alert: It Won’t.  Every time a new technology shows up, someone loudly declares it's the end...",
    readable_publish_date: "Apr 30",
    slug: "will-ai-ruin-society-2e02",
    path: "/besworks/will-ai-ruin-society-2e02",
    url: "https://dev.to/besworks/will-ai-ruin-society-2e02",
    comments_count: 6,
    public_reactions_count: 12,
    collection_id: null,
    published_timestamp: "2025-04-30T18:37:31Z",
    language: "en",
    subforem_id: 1,
    positive_reactions_count: 12,
    cover_image: null,
    social_image:
      "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fjwfzshgamm57w6dk3pw4.png",
    canonical_url: "https://dev.to/besworks/will-ai-ruin-society-2e02",
    created_at: "2025-04-30T18:37:32Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2025-04-30T18:37:31Z",
    last_comment_at: "2025-05-01T00:42:49Z",
    reading_time_minutes: 2,
    tag_list: ["discuss", "ai", "chatgpt", "community"],
    tags: "discuss, ai, chatgpt, community",
    user: {
      name: "Besworks",
      username: "besworks",
      twitter_username: null,
      github_username: "besworks",
      user_id: 841519,
      website_url: "https://bes.works",
      profile_image:
        "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F841519%2Fea3eeabb-6a2d-4b5b-8ab3-aa5b7a00c309.png",
      profile_image_90:
        "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F841519%2Fea3eeabb-6a2d-4b5b-8ab3-aa5b7a00c309.png",
    },
    flare_tag: {
      name: "discuss",
      bg_color_hex: "#71EA8B",
      text_color_hex: "#FFFFFF",
    },
  },
  {
    type_of: "article",
    id: 2439179,
    title: "I Built an MCP Server for DevTo (100% Open Source)🎉",
    description:
      "MCP is Trending Everywhere! Of course, for a Good Reason!  Since launch, It has seen a wide adoption...",
    readable_publish_date: "Apr 28",
    slug: "i-built-an-mcp-server-for-devto-100-open-source-4f6n",
    path: "/arindam_1729/i-built-an-mcp-server-for-devto-100-open-source-4f6n",
    url: "https://dev.to/arindam_1729/i-built-an-mcp-server-for-devto-100-open-source-4f6n",
    comments_count: 33,
    public_reactions_count: 172,
    collection_id: null,
    published_timestamp: "2025-04-28T12:29:59Z",
    language: "en",
    subforem_id: 1,
    positive_reactions_count: 172,
    cover_image:
      "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fnp3ect5dfyybse9i945f.png",
    social_image:
      "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fnp3ect5dfyybse9i945f.png",
    canonical_url:
      "https://dev.to/arindam_1729/i-built-an-mcp-server-for-devto-100-open-source-4f6n",
    created_at: "2025-04-27T20:40:17Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2025-04-28T12:29:59Z",
    last_comment_at: "2025-04-30T15:59:03Z",
    reading_time_minutes: 3,
    tag_list: ["mcp", "devto", "python", "opensource"],
    tags: "mcp, devto, python, opensource",
    user: {
      name: "Arindam Majumder ",
      username: "arindam_1729",
      twitter_username: "Arindam_1729",
      github_username: "Arindam200",
      user_id: 965723,
      website_url: "https://www.arindammajumder.com/",
      profile_image:
        "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F965723%2Fe0982512-4de1-4154-b3c3-1869d19e9ecc.png",
      profile_image_90:
        "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F965723%2Fe0982512-4de1-4154-b3c3-1869d19e9ecc.png",
    },
  },
  {
    type_of: "article",
    id: 2447284,
    title:
      "Built an Extension for GitHub Copilot to save, share and build rules for AI for you",
    description:
      "The team and I over at SpecStory love agentic-first coding.  Built an extension for GitHub Copilot...",
    readable_publish_date: "Apr 30",
    slug: "built-an-extension-for-github-copilot-to-save-share-and-build-rules-for-ai-for-you-lbc",
    path: "/gregce10/built-an-extension-for-github-copilot-to-save-share-and-build-rules-for-ai-for-you-lbc",
    url: "https://dev.to/gregce10/built-an-extension-for-github-copilot-to-save-share-and-build-rules-for-ai-for-you-lbc",
    comments_count: 1,
    public_reactions_count: 11,
    collection_id: null,
    published_timestamp: "2025-04-30T01:20:49Z",
    language: "en",
    subforem_id: 1,
    positive_reactions_count: 11,
    cover_image: null,
    social_image:
      "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fv79xgu37dm46keqosroj.png",
    canonical_url:
      "https://dev.to/gregce10/built-an-extension-for-github-copilot-to-save-share-and-build-rules-for-ai-for-you-lbc",
    created_at: "2025-04-30T01:20:50Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2025-04-30T01:20:49Z",
    last_comment_at: "2025-04-30T14:41:15Z",
    reading_time_minutes: 1,
    tag_list: ["ai", "vscode", "githubcopilot"],
    tags: "ai, vscode, githubcopilot",
    user: {
      name: "Greg Ceccarelli",
      username: "gregce10",
      twitter_username: null,
      github_username: null,
      user_id: 2749139,
      website_url: "https://specstory.com",
      profile_image:
        "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F2749139%2F29ac4de5-755e-4e59-9548-5f4fa7e7b60b.jpeg",
      profile_image_90:
        "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F2749139%2F29ac4de5-755e-4e59-9548-5f4fa7e7b60b.jpeg",
    },
  },
  {
    type_of: "article",
    id: 2442304,
    title: "Top 7 Featured DEV Posts of the Week",
    description:
      "Welcome to this week's Top 7, where the DEV editorial team handpicks their favorite posts from the...",
    readable_publish_date: "Apr 29",
    slug: "top-7-featured-dev-posts-of-the-week-2li0",
    path: "/devteam/top-7-featured-dev-posts-of-the-week-2li0",
    url: "https://dev.to/devteam/top-7-featured-dev-posts-of-the-week-2li0",
    comments_count: 2,
    public_reactions_count: 25,
    collection_id: null,
    published_timestamp: "2025-04-29T13:53:40Z",
    language: "en",
    subforem_id: 1,
    positive_reactions_count: 25,
    cover_image:
      "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fyg1hz88tsa34wykeqzta.jpg",
    social_image:
      "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fyg1hz88tsa34wykeqzta.jpg",
    canonical_url:
      "https://dev.to/devteam/top-7-featured-dev-posts-of-the-week-2li0",
    created_at: "2025-04-28T14:57:52Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2025-04-29T13:53:40Z",
    last_comment_at: "2025-04-30T16:56:32Z",
    reading_time_minutes: 2,
    tag_list: ["top7"],
    tags: "top7",
    user: {
      name: "dev.to staff",
      username: "thepracticaldev",
      twitter_username: "ThePracticalDev",
      github_username: null,
      user_id: 3,
      website_url: "https://dev.to",
      profile_image:
        "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png",
      profile_image_90:
        "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png",
    },
    organization: {
      name: "The DEV Team",
      username: "devteam",
      slug: "devteam",
      profile_image:
        "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
      profile_image_90:
        "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
    },
  },
  {
    type_of: "article",
    id: 2443873,
    title:
      "Coding faster is not building better: A reflection for developers in the AI era",
    description:
      "The rise of AI coding assistants like Claude, GitHub Copilot and ChatGPT has transformed the way we...",
    readable_publish_date: "Apr 29",
    slug: "coding-faster-is-not-building-better-a-reflection-for-developers-in-the-ai-era-34fk",
    path: "/mr_stone/coding-faster-is-not-building-better-a-reflection-for-developers-in-the-ai-era-34fk",
    url: "https://dev.to/mr_stone/coding-faster-is-not-building-better-a-reflection-for-developers-in-the-ai-era-34fk",
    comments_count: 21,
    public_reactions_count: 22,
    collection_id: null,
    published_timestamp: "2025-04-29T01:40:39Z",
    language: "en",
    subforem_id: 1,
    positive_reactions_count: 22,
    cover_image:
      "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fqp15cc6thui5mc4htxhb.png",
    social_image:
      "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fqp15cc6thui5mc4htxhb.png",
    canonical_url:
      "https://dev.to/mr_stone/coding-faster-is-not-building-better-a-reflection-for-developers-in-the-ai-era-34fk",
    created_at: "2025-04-29T01:40:40Z",
    edited_at: "2025-04-29T02:00:42Z",
    crossposted_at: null,
    published_at: "2025-04-29T01:40:39Z",
    last_comment_at: "2025-04-30T23:11:50Z",
    reading_time_minutes: 1,
    tag_list: ["ai", "softwaredevelopment", "futureofwork", "developers"],
    tags: "ai, softwaredevelopment, futureofwork, developers",
    user: {
      name: "Mr. Stone",
      username: "mr_stone",
      twitter_username: null,
      github_username: null,
      user_id: 3102675,
      website_url: null,
      profile_image:
        "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3102675%2F74fd563f-5569-46a6-9c91-5f655741df8d.png",
      profile_image_90:
        "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3102675%2F74fd563f-5569-46a6-9c91-5f655741df8d.png",
    },
  },
  {
    type_of: "article",
    id: 2445163,
    title: "Vibe coding for a gamejam",
    description:
      "So recently, there was a gamejam from GameDev.js to produce a web game, in less than a week.  A total...",
    readable_publish_date: "Apr 29",
    slug: "vibe-coding-for-a-gamejam-4k9h",
    path: "/jacklehamster/vibe-coding-for-a-gamejam-4k9h",
    url: "https://dev.to/jacklehamster/vibe-coding-for-a-gamejam-4k9h",
    comments_count: 2,
    public_reactions_count: 10,
    collection_id: null,
    published_timestamp: "2025-04-29T10:02:12Z",
    language: "en",
    subforem_id: 1,
    positive_reactions_count: 10,
    cover_image:
      "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Flkubniplfs1ph7wgx43d.png",
    social_image:
      "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Flkubniplfs1ph7wgx43d.png",
    canonical_url:
      "https://dev.to/jacklehamster/vibe-coding-for-a-gamejam-4k9h",
    created_at: "2025-04-29T09:53:11Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2025-04-29T10:02:12Z",
    last_comment_at: "2025-04-30T04:54:28Z",
    reading_time_minutes: 6,
    tag_list: ["gamedev", "vibecoding", "cursor", "ai"],
    tags: "gamedev, vibecoding, cursor, ai",
    user: {
      name: "Jack Le Hamster",
      username: "jacklehamster",
      twitter_username: "jacklehamster",
      github_username: "jacklehamster",
      user_id: 1004190,
      website_url: "https://dobuki.net",
      profile_image:
        "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1004190%2F1c584c56-fcbb-4401-88c5-f6de459dd72f.jpeg",
      profile_image_90:
        "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1004190%2F1c584c56-fcbb-4401-88c5-f6de459dd72f.jpeg",
    },
  },
  {
    type_of: "article",
    id: 2442044,
    title: "Meme Monday",
    description:
      "Meme Monday!  Today's cover image comes from last week's thread.  DEV is an inclusive space! Humor in...",
    readable_publish_date: "Apr 28",
    slug: "meme-monday-1l21",
    path: "/ben/meme-monday-1l21",
    url: "https://dev.to/ben/meme-monday-1l21",
    comments_count: 64,
    public_reactions_count: 36,
    collection_id: null,
    published_timestamp: "2025-04-28T13:16:20Z",
    language: "en",
    subforem_id: 1,
    positive_reactions_count: 36,
    cover_image:
      "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F340k79nabgzl41l24d8g.png",
    social_image:
      "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F340k79nabgzl41l24d8g.png",
    canonical_url: "https://dev.to/ben/meme-monday-1l21",
    created_at: "2025-04-28T13:16:21Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2025-04-28T13:16:20Z",
    last_comment_at: "2025-04-30T17:21:36Z",
    reading_time_minutes: 1,
    tag_list: ["watercooler", "discuss", "jokes"],
    tags: "watercooler, discuss, jokes",
    user: {
      name: "Ben Halpern",
      username: "ben",
      twitter_username: "bendhalpern",
      github_username: "benhalpern",
      user_id: 1,
      website_url: "http://benhalpern.com",
      profile_image:
        "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1%2Ff451a206-11c8-4e3d-8936-143d0a7e65bb.png",
      profile_image_90:
        "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1%2Ff451a206-11c8-4e3d-8936-143d0a7e65bb.png",
    },
    flare_tag: {
      name: "watercooler",
      bg_color_hex: "#D0ECFF",
      text_color_hex: "#130074",
    },
  },
  {
    type_of: "article",
    id: 2430207,
    title: "A Decade of SolidJS",
    description:
      "As of today, it has been 7 years since I open-sourced SolidJS. It wasn't for noble reasons. I wasn't...",
    readable_publish_date: "Apr 24",
    slug: "a-decade-of-solidjs-32f4",
    path: "/this-is-learning/a-decade-of-solidjs-32f4",
    url: "https://dev.to/this-is-learning/a-decade-of-solidjs-32f4",
    comments_count: 25,
    public_reactions_count: 168,
    collection_id: null,
    published_timestamp: "2025-04-24T18:48:10Z",
    language: "en",
    subforem_id: 1,
    positive_reactions_count: 168,
    cover_image:
      "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fudmmdvhspu20i4i1ax4t.png",
    social_image:
      "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fudmmdvhspu20i4i1ax4t.png",
    canonical_url: "https://dev.to/this-is-learning/a-decade-of-solidjs-32f4",
    created_at: "2025-04-24T14:51:26Z",
    edited_at: "2025-04-25T06:46:30Z",
    crossposted_at: null,
    published_at: "2025-04-24T18:48:10Z",
    last_comment_at: "2025-04-30T14:53:33Z",
    reading_time_minutes: 10,
    tag_list: ["javascript", "webdev", "solidjs", "devjournal"],
    tags: "javascript, webdev, solidjs, devjournal",
    user: {
      name: "Ryan Carniato",
      username: "ryansolid",
      twitter_username: "RyanCarniato",
      github_username: "ryansolid",
      user_id: 186199,
      website_url: "https://solidjs.com",
      profile_image:
        "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F186199%2Fa3d1cfed-a1ca-41cd-a146-9db4e65711d4.jpeg",
      profile_image_90:
        "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F186199%2Fa3d1cfed-a1ca-41cd-a146-9db4e65711d4.jpeg",
    },
    organization: {
      name: "This is Learning",
      username: "this-is-learning",
      slug: "this-is-learning",
      profile_image:
        "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F3314%2Fdc73eb74-08f9-4592-b599-c08f2bb14b4d.png",
      profile_image_90:
        "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F3314%2Fdc73eb74-08f9-4592-b599-c08f2bb14b4d.png",
    },
  },
];
